backend:
  name: git-gateway
  branch: main
  site_id: dynamic-bunny-30612e.netlify.app

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  # Navbar
  - name: "navbar"
    label: "Navbar"
    files:
      - file: "content/navbar/navbar.md"
        label: "Navbar Content"
    fields:
      - { label: "Logo Image", name: "logo_image", widget: "image" }
      - { label: "Logo Alt Text", name: "logo_alt", widget: "string" }
      - { label: "Menu Items", name: "menu_items", widget: "list", fields: [
          { label: "Text", name: "text", widget: "string" },
          { label: "Link", name: "link", widget: "string" }
        ] }

  # Slider (folder-based - correct as-is)
  - name: "slider"
    label: "Slider"
    folder: "content/slider"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Background Image", name: "background_image", widget: "image" }
      - { label: "Button Text", name: "button_text", widget: "string", required: false }
      - { label: "Button Link", name: "button_link", widget: "string", required: false }

  # About Us
  - name: "about"
    label: "About Us"
    files:
      - file: "content/about/about.md"
        label: "About Page"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  # Core Focus
  - name: "focus"
    label: "Core Focus"
    files:
      - file: "content/focus/focus.md"
        label: "Core Focus Content"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  # News (folder-based - correct as-is)
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }

  # Events (folder-based - correct as-is)
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Event Date", name: "event_date", widget: "datetime" }

  # Creating Opportunities
  - name: "opportunities"
    label: "Creating Opportunities"
    files:
      - file: "content/opportunities/opportunities.md"
        label: "Opportunities Content"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  # Sustainable Development
  - name: "sustainable"
    label: "Sustainable Development"
    files:
      - file: "content/sustainable/sustainable.md"
        label: "Sustainable Development Content"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  # Our Strategy
  - name: "strategy"
    label: "Our Strategy"
    files:
      - file: "content/strategy/strategy.md"
        label: "Strategy Content"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Services", name: "services", widget: "list", field: {label: "Service", name: "service", widget: "string"} }

  # Our Impact (folder-based - correct as-is)
  - name: "impact"
    label: "Our Impact"
    folder: "content/impact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }

  # Our Commitment
  - name: "commitment"
    label: "Our Commitment"
    files:
      - file: "content/commitment/commitment.md"
        label: "Commitment Content"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "SDG Image", name: "sdg_image", widget: "image" }

  # Where We Work
  - name: "locations"
    label: "Where We Work"
    files:
      - file: "content/locations/locations.md"
        label: "Locations Content"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  # Team (folder-based - correct as-is)
  - name: "team"
    label: "Team"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

  # Let's Connect
  - name: "contact"
    label: "Contact Us"
    files:
      - file: "content/contact/contact.md"
        label: "Contact Page"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Address", name: "address", widget: "markdown" }
      - label: "Form Settings"
        name: "form"
        widget: "object"
        fields:
          - { label: "Submit Button Text", name: "submit_text", widget: "string", default: "Submit" }
          - { label: "Success Message", name: "success_message", widget: "string", default: "Thank you for your message! We'll get back to you soon." }

  # Footer
  - name: "footer"
    label: "Footer"
    files:
      - file: "content/footer/footer.md"
        label: "Footer Content"
    fields:
      - { label: "Copyright Text", name: "copyright_text", widget: "string" }
      - { label: "Additional Content", name: "content", widget: "markdown", required: false }